apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  type: LoadBalancer
  selector:
    app: mqtt
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    - name: websocket
      port: 9001
      targetPort: websocket
      protocol: TCP
