apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-ops
resources:
  - ../../../base/postgres
  - sealed-secret.yaml
patches:
  - path: patch-pvc.yaml
  - path: patch-secret.yaml
