---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: home-ops
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBEXeaSgGgGOtVy7YshD4n0nUnM8+VYpqxJoF97Z4sjO1P+gLjIPzLTkAVO7tIqyrWWA7mWGVqQApmLbHVWENH12znug3JR9/ArJqUi29XPmAvQwCyudzvGEuPFgpuxDicHqGySTaZDZn5TZWw7RFVoPrqKuCJApal3L0s2H3sQZXMpZfitPtw6BClQRSVnyOV/XR6O7hL/dFHZMl6aoH97KrlwvRP1wXPWG9+nBmQHj/F+vL5DW/f4UFBkRw7NRLX1ffgxh00re4djL98/y6FX6vN+ZAGj1Yi7B0V/7i01VRgszH4a2OYcJ6+Sh0VTcH2+slMeyOpiwCxqk1V3UTKdpVezgUWKVHs1z7AbzooqdRYwpIPBeLbIeDWLnOntfLcv4teAspLueoRMD4Tb+DC2Pc4WvWwW80J6W/dIpzGaKlgXq5OnsdDaMw31UoKDwTDXMlXMYvD0EGkJiq00GcPIyKP1wcuRaD/u2vJxzYseDuUTUU+2Oy4RiX0V8qyYoyykRyoSbSeyf3bsjOYq5MxQ2kR1S6FZcfECcFXMShKGaxtPEJPV7Z6JNDRmQUZCOoYNgscWqEeZ/1jMCwPIz9nGCYGOv91GIlmJI4BcjY0ci36hIYyu3Vk2ZMb1E4ppc7CUdcvF317cHGrADd/PuK1232nAbwrzcEy23su2EAYkabcN+ea3IPPT7gHi5D22mFjXnfhifWF4cSVOV+wOPsqNuK47Sg==
    POSTGRES_USER: AgCzDXqxaq9CIDQCPhkHGHJf41ZcJzmzYBXBxsCD9SxLg3Uc8QpYmM0dGdo4TwOu3DtCKCQk8H/qQeR5wLKGVMEHq1zPhisunZM3MfCigBiEGkDKuZZCKhI2KuZqvbSeuk8gMvE5NAScbgbE3X9C58OVuBacJReSZmER7/hFbE4DZPPjbepKKZGoeYF9MBJV1arfYUzS/kK0rEWGlUJpNGJkR88Fxga4kvT/ifbNl2kqdT2KwjlnhZgkMHGNf1bOS0DnSI1L1/gySiB9rWheCf54huCbYFB0U1Bc6bdPVUS0MQfJzmOBKxQYjukCVRMwYhi6LiXhPJgcQxM5JyPN2JvWk38KZ8dlKVPtiXFOVEWZBUkXXP0vU6ToFegnfKe/921T5rkWTITiU72Lv3Gku9vwCnvaYTP6ARxJhO/PWcQBnCER3MDzAxjkFwz4WKmqDEHlu9kQPYnmq+7I4Qbwb0vpaQqu3E9/RBUrvdubtCDdjdjH5TjHceLBbIb0RQNWi3GJ83CMe0geDg39vTE7VbAU9Fcu9a2kGMTlt7kNIBMp6n3t/CNvFmbYel7xDJMSu1nGmHHCNgo3i64Du2TsUITIgJTgBuRKQOThPMtWyrSiMYRH9AYySJFlN8fPa2+t+Jn4KieNJqgxf4Ns0IkGYjRsZzax1Lbh8RdYlZSiGTgDujqWNy++NAD7ezOp5sI71WZ3FqRcN0VjH30JJtMn
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: home-ops
