apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5234
      targetPort: postgres
      protocol: TCP
