apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-ops-esphome
  namespace: argocd
spec:
  project: home-ops
  destination:
    server: https://kubernetes.default.svc
    namespace: home-ops
  source:
    repoURL: https://github.com/epaulsen/home-ops.git
    targetRevision: main
    path: k8s/overlays/nuc-prod/esphome
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
