apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-data
spec:
  storageClassName: local-path
  volumeName: node-red-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
