apiVersion: v1
kind: Service
metadata:
  name: whisper
spec:
  type: LoadBalancer
  selector:
    app: whisper
  ports:
    - name: wyoming
      port: 10300
      targetPort: wyoming
      protocol: TCP
