apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-data-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/epaulsen/containers/hass/mosquitto-data
    type: DirectoryOrCreate
