apiVersion: v1
kind: PersistentVolume
metadata:
  name: whisper-data-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/epaulsen/containers/hass/whisper-data
    type: DirectoryOrCreate
